import ExternalLink from "@/components/ExternalLink";
import InternalLink from "@/components/InternalLink";

export default function About() {
    return (
        <>
            <div className="mt-10"></div>
            <InternalLink label="Home" href="/"/>
            <div className="flex justify-center">
                <div className="bg-zinc-700 rounded-2xl mt-5 p-6 lg:p-10 w-full">
                    <h2 className="text-xl lg:text-3xl mb-4 lg:mb-7">
                        About                
                    </h2>

                    <p className="text-sm lg:text-lg mb-3 lg:mb-5">
                        I built this app in a little over a week as a hobby project.
                        It uses the MusicBrainz and SetlistFM APIs to collect data on artist&apos;s concert histories,
                        which you can then explore in an interactive map powered by MapLibre and MapTiler.
                    </p>
                    <p className="text-sm lg:text-lg mb-3 lg:mb-5">
                        The predictions are generated by Gemini and only take into account historical data.
                        Data is cached in MongoDB for up to 3 days which might mean that recent events are not accounted for.
                    </p>
                    <p className="text-sm lg:text-lg mb-6 lg:mb-9">
                        You can view the source code on GitHub. If you liked this app, you can support me on Ko-Fi. Thank you!
                    </p>

                    <div className="flex flex-wrap gap-3">
                        <ExternalLink label={"Source code on GitHub"} href={"https://github.com/jparkes04/WhenTouring"}></ExternalLink>
                        <ExternalLink label={"Buy me a coffee"} href={"https://ko-fi.com/jparkes"}></ExternalLink>
                        <ExternalLink label={"SetlistFM"} href={"https://www.setlist.fm/"}></ExternalLink>
                        <ExternalLink label={"MusicBrainz"} href={"https://musicbrainz.org/"}></ExternalLink>
                        <ExternalLink label={"MapLibre"} href={"https://maplibre.org/"}></ExternalLink>
                        <ExternalLink label={"MapTiler"} href={"https://www.maptiler.com/"}></ExternalLink>
                        <ExternalLink label={"React Map GL"} href={"https://visgl.github.io/react-map-gl/"}></ExternalLink>
                    </div>

                </div>
            </div>

        </>
    )
}